In [122]:
import torch
from torchvision import transforms, datasets
import os
import numpy as np
from torch.nn import functional as F
from torch.utils.data import DataLoader
import tarfile
from torchvision.datasets.utils import download_url

In [123]:
dataset_url = "http://pjreddie.com/media/files/cifar.tgz"
download_url(dataset_url,'.')
with tarfile.open('./cifar.tgz','r') as tar:
    tar.extractall(path='./data1')

Using downloaded and verified file: .\cifar.tgz


In [173]:
# Look into the data directory
data_dir = './data1/cifar'
print(os.listdir(data_dir))


['labels.txt', 'test', 'train']


In [154]:
with open(os.path.join(data_dir, 'labels.txt'), "r", encoding="utf-8") as f:
    data = f.read()
labels = data.split('\n')
if '' in labels:
    labels.remove('')
labels

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [155]:
train_test_folder = [sub_dir for sub_dir in os.listdir(data_dir) if os.path.isdir(os.path.join(data_dir,sub_dir))]
train_test_folder

['test', 'train']

In [157]:
for each in train_test_folder:
    for cls_name in labels:
        if not os.path.exists(os.path.join(data_dir, each, cls_name)):
            os.mkdir(os.path.join(data_dir, each, cls_name))     

In [159]:
import shutil

In [161]:
for each in train_test_folder:
    for src_path in glob.glob(os.path.join(data_dir, each, "*.png")):
        dest_path = os.path.join(data_dir, each, (os.path.basename(src_path).split("_")[1].split('.')[0]))
        shutil.move(src_path,dest_path)

    

In [177]:
from torch.utils.data import DataLoader

In [178]:
stats = ((0.4914, 0.4822, 0.4465),(0.2023, 0.1994, 0.2010))

Data Augmentation should be done only on the Traning images and not on the validation images

In [170]:
train_transforms = transforms.Compose([
    transforms.RandomCrop(32, padding=4, padding_mode='reflect'),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(*stats, inplace=True) # modify the existing tensors without making copy
])
validation_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(*stats)
])

In [179]:
# pytorch datasets
from torchvision.datasets import ImageFolder
train_dataset1 = ImageFolder(data_dir + "/train")
valid_dataset1 = ImageFolder(data_dir + "/test")


In [85]:
from tqdm.notebook import tqdm

In [86]:
mean_sum_r, mean_sum_g, mean_sum_b = 0,0,0
std_sum_r, std_sum_g, std_sum_b = 0,0,0
import glob
import os
from PIL import Image
import numpy as np
data_dir = './data/cifar'
all_mean_rgb= [0, 0, 0]
all_std_rgb = [0, 0, 0]
for img_path in tqdm(glob.glob(os.path.join(data_dir, 'train',"*.png"))):
    
    img = Image.open(img_path)
    
    img_np = np.asarray(img)
    mean_rgb = img_np.mean(axis=(0,1))
    std_rgb = img_np.std(axis=(0,1))
    all_mean_rgb = all_mean_rgb + mean_rgb
    all_std_rgb = all_std_rgb + std_rgb

    
        
    
    
    

C:\Users\Senthilkumar\AppData\Local\Temp\ipykernel_2104\2495341476.py:10: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for img_path in tqdm_notebook(glob.glob(os.path.join(data_dir, 'train',"*.png"))):


  0%|          | 0/50000 [00:00<?, ?it/s]

In [91]:
all_mean_rgb/(50000*32*32)

array([0.12237004, 0.12006874, 0.11119666])

In [92]:
all_std_rgb/(50000*32*32)

array([0.05035307, 0.04963421, 0.05001971])

In [88]:
all_std_rgb

array([2578076.99182133, 2541271.57525891, 2561009.13732902])

In [105]:
from torch.utils.data import Dataset


In [119]:
class Custom_cifar10(Dataset):
    def __int__(self):
        self.img_dir = r"./data/cifar/train"

    def __len__(self):
        classes = [each.split('_')[1].split('.')[0] for each in os.listdir(self.img_dir)]
        cls_dict = {}
        for cls in set(classes):
            cls_len = len([each for each in classes if cls==each])
            cls_dict[cls]=cls_len
        return cls_dict
        
        

In [120]:
Custom_cifar10()

In [121]:
len(Custom_cifar10())

AttributeError: 'Custom_cifar10' object has no attribute 'img_dir'

In [10]:
import numpy as np

In [15]:
arr = np.array([[[1,1,1],[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2],[2,2,2]],[[3,3,3],[3,3,3],[3,3,3],[3,3,3]],[[4,4,4],[4,4,4],[4,4,4],[4,4,4]]])

In [16]:
arr.shape

(4, 4, 3)

In [81]:
arr.mean(axis=(0,1))

array([2.5, 2.5, 2.5])

In [25]:
import torch

In [28]:
tensor = torch.from_numpy(arr)
tensor.shape

torch.Size([4, 4, 3])

In [37]:
tensor_float = tensor.float()

In [80]:
tensor_float.mean(dim=(0,1))

tensor([2.5000, 2.5000, 2.5000])

In [62]:
tensor_float[:,:,0].mean()

tensor(2.5000)

In [47]:
tensor_float[:,:,1]

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])